name: ecoli-variant-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastqc=0.12.1
  - fastp=0.12.4
  - multiqc=1.35
  - bwa=0.7.15
  - samtools=1.13
  - bcftools=1.23.1
  - snpeff=4.3.1.t
